"""initial tables

Revision ID: 1c27d577d57e
Revises: 
Create Date: 2026-02-24 15:18:52.643770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c27d577d57e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_flag',
    sa.Column('flag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('flag_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('flag_id')
    )
    op.create_index(op.f('ix_player_flag_player_id'), 'player_flag', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_flag_timestamp'), 'player_flag', ['timestamp'], unique=False)
    op.create_index('ix_game_events_player_timestamp', 'game_events', ['player_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_events_player_timestamp', table_name='game_events')
    op.drop_index(op.f('ix_player_flag_timestamp'), table_name='player_flag')
    op.drop_index(op.f('ix_player_flag_player_id'), table_name='player_flag')
    op.drop_table('player_flag')
    # ### end Alembic commands ###
