"""make player_flag columns not null

Revision ID: 24846f3f43fc
Revises: c414b294e826
Create Date: 2026-08-05 12:58:16.189089

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24846f3f43fc'
down_revision: Union[str, None] = 'c414b294e826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_flag', 'player_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player_flag', 'flag_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player_flag', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('player_flag', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('player_flag', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_flag', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player_flag', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('player_flag', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player_flag', 'flag_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('player_flag', 'player_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
