"""add_timestamp_index

Revision ID: 755a139ce3cd
Revises: c1c7ee13c83b
Create Date: 2026-04-21 12:11:00.207413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755a139ce3cd'
down_revision: Union[str, None] = 'c1c7ee13c83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_game_events_timestamp', 'game_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_events_timestamp', table_name='game_events')
    # ### end Alembic commands ###
