"""add event_data column to game_events

Revision ID: c1c7ee13c83b
Revises: 1c27d577d57e
Create Date: 2026-03-26 13:34:44.306689

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c7ee13c83b'
down_revision: Union[str, None] = '1c27d577d57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'game_events', 
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_events', 'event_data')
    # ### end Alembic commands ###
